FROM python:3.11.4-slim-buster

WORKDIR /app

ENV PYTHONPATH=/app
ENV FLASK_APP=src/app.py

COPY requirements-dev.txt requirements-dev.txt
COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements-dev.txt && \
    pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["jupyter", "notebook", "--ip=0.0.0.0.", "--allow-root", "--no-browser", "--NotebookApp.token=''"]
